# Use the SQL Server 2019 image from Microsoft
FROM mcr.microsoft.com/mssql/server:2019-latest

# Install sqlcmd
USER root
RUN apt-get update && apt-get install -y mssql-tools unixodbc-dev
ENV PATH="$PATH:/opt/mssql-tools/bin"

# Switch back to the mssql user
USER mssql

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=%ZoporTe*2023

# Expose SQL Server port
EXPOSE 1433
